Default to empty string if q param is missing
Error occurred because the `params.fetch("q", "")` returns `nil` if q param is missing in the query, and calling squish on nil raises the NoMethodError.

params["q"] will return nil if the key doesn't exist, and || will fall back to "" (an empty string) if that's the case

https://govuk.sentry.io/issues/6194636580/?project=1461892

NoMethodError
undefined method `squish' for nil:NilClass (NoMethodError)

      query_param = params.fetch("q", "").squish