Fix previews when some data rows are nil
We were seeing an error when `row[index]` is nil.

`row[index].try(:[], :format)` won’t raise an error and return nil. Otherwise it will safely check the :format key.

https://govuk.sentry.io/issues/6195895254/?project=1461892
NoMethodError
undefined method `[]' for nil:NilClass (NoMethodError)

Unrelated to Solr DB migration.