Handle nil values in is_numeric
This method assumes that the input is a string, however it is quite
possible that a CSV contains nil values. This is causing a crash in
production with error:

'ActionView::Template::Error: undefined method `match?' for nil:NilClass'